name: Build

on:
  workflow_call:
    inputs:
        python_version:
          description: "Python version"
          type: string
          required: false
          default: "3.12"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ inputs.python_version }}
        uses: actions/setup-python@v4
        with:
            python-version: ${{ inputs.python_version }}
      - name: Install dependencies
        run: |
            python -m pip install --upgrade pip
            pip install poetry
            poetry install
      - name: Build application
        run: |
            poetry build
      - name: Test with pytest
        run: |
            poetry run pytest