name: Publish to PyPi
on:
  workflow_call:
    inputs:
      python_version:
        description: "Python version"
        type: string
        required: false
        default: "3.12"
    secrets:
      PYPI_API_KEY:
        description: "PyPi API Token"
        required: true

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ inputs.python_version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ inputs.python_version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
      - name: Build
        run: |
          poetry build
      - name: Publish to PyPi
        run: |
          poetry config pypi-token.pypi ${{ secrets.PYPI_API_KEY}}
          poetry publish
