name: Push to Main

on:
  push:
    branches: [ main ]

jobs:
  build:
    uses: ./.github/workflows/build.yml

  publish:
    needs: build
    uses: ./.github/workflows/publish.yml
    secrets:
      PYPI_API_KEY: ${{ secrets.PYPI_API_KEY }}
